docs: API extensibility
vmware/cloud-director-extension-standard-library pull request #39
Opened 2024-03-14 13:23 UTC by kirilkadoncheva

This commit contains API extensibility via MQTT and API extensibility via HTTP documentation.

Signed-off-by: Kirilka Doncheva donchevak@vmware.com

2024-04-03 08:21 UTC, iiliev2 requested changes

2024-04-03 08:21 UTC, iiliev2 commented on documentation/extensibility-platform/api-extensibility.md
> +Let's say we have an external service registeres and an API filter with the following urlPattern - `/api/org/.*/currentTime`. If we want a link to this custom URL to be returned each time a GET is ex
>returned each time a GET is executed on an **organization**

It is rather unclear why/how this works. It must be pointed out that `ResourceType` has to be set.

2024-04-03 08:21 UTC, iiliev2 commented on documentation/extensibility-platform/api-extensibility.md
> +    <ns2:ResourceType>application/vnd.vmware.admin.vcloud+xml</ns2:ResourceType>
This is not the organisation mime type(`application/vnd.vmware.vcloud.org+xml`)

2024-04-03 08:21 UTC, iiliev2 commented on documentation/extensibility-platform/api-extensibility.md
> +        "id": "urn:vcloud:extensionEndpoint:vmware:test:1.0.0",
This id seems to be of an `External Endpoint`, not `External Service`
Other places too

2024-04-03 08:21 UTC, iiliev2 commented on documentation/extensibility-platform/api-extensibility.md
> +### MQTT Shared subscriptions
This section seems out of topic not only in the context of this page, but for Cloud Director in general.
In this page at most you can mention that when deploying the external service backends, mqtt 5 shared subscriptions may be used to horizontally scale the load(starting Cloud Director 10.6).

Any of the other details that you put in this section should be moved to `message-broker.md`, however that file currently only describes the mqtt 3 capabilities(see the top), as mqtt 5 support is not yet officially released.
These details should be put in the context of Cloud Director. Do not just describe the general capabilities of the protocol, but how Cloud Director implements them(are there any limitations/nuances, etc). I am not sure we need to put anything at this point. We do not have an official statement on for example the load balancing strategy.

2024-04-03 15:20 UTC, vmonov submitted a review, later dismissed
Good job on the docs and the example JAVA code!
One overall suggestion I have is to run the text through chatGPT for any errors and better structure of the text here and there, but first take out any VCD internals in the doc.

2024-04-03 15:20 UTC, vmonov commented on documentation/extensibility-platform/api-extensibility.md
> +### Resource Class
Are the contents of the section not too VCD internals specific? Maybe we should consider skipping info for things like Entity Resolver to avoid confusion.

2024-05-09 11:43 UTC, kirilkadoncheva commented on documentation/extensibility-platform/api-extensibility.md
> +Let's say we have an external service registeres and an API filter with the following urlPattern - `/api/org/.*/currentTime`. If we want a link to this custom URL to be returned each time a GET is ex
In this case a Resource Type does not have to be set in this case - the organization is a core VCD entity.

2024-06-11 11:28 UTC, kirilkadoncheva commented on documentation/extensibility-platform/api-extensibility.md
> +### Resource Class
VCD Entity Resolver is publivly used terminology https://blogs.vmware.com/vsphere/2012/05/entity-resolver-in-the-vcloud-api.html

2024-06-11 11:29 UTC, kirilkadoncheva commented on documentation/extensibility-platform/api-extensibility.md
> +    The authorization rules are defined in the context of a Resource Class. As previously said, the Resource Class represents an external resource type in Cloud Director ([more info](#resource-class)
Yes and that access must be granted via an ACL Rule.

2024-08-12 06:55 UTC, ttonchevvmware approved these changes

2024-08-12 06:58 UTC, theotonchev approved these changes

2024-08-12 08:14 UTC, iiliev2 approved these changes
IMO we should take the better parts of the old api programming guide and use that information in this guide. The old guide was just missing some newer functionality(obviously the MQTT part). Both are missing the description of long running operations, where Cloud Director manages the task.

2024-08-12 08:46 UTC, merged